language: bash
sudo: true
services:
- docker
before_install:
- docker info
- docker version
- echo "==> Build with Docker ..."
- docker build -f tests/alpine-3/Dockerfile     -t gitbook:alpine-3      . | tee tests/output.alpine-3.log
- docker build -f tests/ubuntu-14.04/Dockerfile -t gitbook:ubuntu-14.04  . | tee tests/output.ubuntu-14.04.log
script:
- echo "==> Run Test case ..."
- grep "GitBook version" tests/output.alpine-3.log
- grep "GitBook version" tests/output.ubuntu-14.04.log
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: HRHqoYovbod2bb8mP7h2u+lcvUwuvEduNLER/5ptZNtfsHY3Tu5dVlKFw7akkLdkX0thhZ/Qpw/n4ZLL+oDDMiLkAtcSj3dEPI/6YPWpqktiARIBEUY4sbs35G2OuUh2YacStfr9FjQAknHYVt56E+k5NYn2SnJeYO0pjJ1hlcTImGPlNPF42gPDFnm0VHzL1nIWzzqWQwLzGCl3oGDf43fKCftH2RO28vchpgZ4MVwxWDad3KFH0R1JEW03aBGWORm2PAxUZBs9cFYeV0EBSu/dO3n/e4oYDxMPQIQ4NDpQoO5vvVsMf60cvSbyMb4FevNUMVGssufQDBaTxX40lkZsCHGxbbVenOr2htO7oekg+JZODViRH4WPaSRMcMpwAFQY10YkZfE6FAkLSF4YJ1l6EeoXQjFuJxIuEjKLsi8Q5tuZHTBgWpP12Z/ug70vxgnpcohU3uaVuv/+5l8Fwclm/IQ6WNmk7V7vjG5KzU/vEb1cY1PnNjswu6wR8ZmWKoT1uL+xXSUFzf7uz3knkwi9FxAkfM3duGCXcPwhqf/LQpEZCT3vRPp8POTaXZCJYR3PMtxnO4Vpk7Kb+upJF//rY09EA/Azs0WQm0o/L/4r3Fhopg/P7Mf6nZaJT2ve0gbQ8/bgnH+fsVDuRO8sM+jteYwSoRLGDhAFiv4LAck=
