language: bash
sudo: true
services:
- docker
before_install:
- docker info
- docker version
- echo "==> Build with Docker ..."
- docker build -f tests/gitbook-2.6/Dockerfile  -t gitbook:2.6          . | tee tests/gitbook-2.6.log
- docker build -f tests/gitbook-3.2/Dockerfile  -t gitbook:3.2          . | tee tests/gitbook-3.2.log
- docker build -f tests/ubuntu-14.04/Dockerfile -t gitbook:ubuntu-14.04 . | tee tests/gitbook-ubuntu-14.04.log
script:
- echo "==> Run Test case ..."
- grep "GitBook version" tests/gitbook-2.6.log
- grep "GitBook version" tests/gitbook-3.2.log
- grep "GitBook version" tests/gitbook-ubuntu-14.04.log
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: p1f/0B4J2Hmhz0tUlF665YI1vy5LKscdT9deC9425sFxqoU3JsHHgt6MjiAzTHiG5oo+d/gfZ7wwyxpTl5RzfeIz4e3dpq+Wi//QwovudGu7Xos5pUaQYBievkRnVwainqTOXXiKpeWGYYfLnWfxvzCvyBoj/DrPR/C07NW4YoJtcLQszsORZGZko4I2ERvWaF6tJnx/EjpWUelA8Z6WfcDxdn0KOYqfrfEmrWECBP7VOPYunRWx4CBYW0Jz/mPIS4KwXCtFCJPXsaCpbCVH6KBaeXVOY+P4qltsxva3R6/sAQK4f87hK2Ijim23UY3Lsyvd/nm/8RMRFSEHpfCRgZfJQJqaBfFmXncaYu1CguzzxjU2/0/pkuTLNnPCypoKsZXbF9ulLlsvlSQEv0DlVgIL9TiVib2AzE1qE5mVtnHA3gbGrdgd7aQkANO9zcv3Dsimlgbp0jsrqpcAC7gqKvhkHcdwepj9XYjiiJC75kw82KNGfhnobaoALh0OoQj4vhQLWfTnUlRWGAN8a/d4wxIT8CVIl6gHc2rbVWutAruI3kslQ9Hp+1ypvOI4qjhctcMdFLKeB25oTMqZ6ZAp4fnzmWcMJs+n4Ff4cClunHpQ4ibuut+zxQSsonJO0BD92IOAurx0FWorV/5D79PPPS4yq6hfBPYXRI8iItWSRcA=
