#!/usr/bin/env ansible-playbook
# ============================================================
#  Author: Chu-Siang Lai / chusiang (at) drx.tw
#  Blog: http://note.drx.tw
#  Filename: setup.yml
#  Modified: 2018-01-12 14:59
#  Description: Setup the GitBook with Ansible Playbooks.
#  Reference:
#
#   - No such file the node - http://stackoverflow.com/a/26320915
#
# ===========================================================
---

- name: Setup the GitBook
  hosts: all
  vars_files:
    - defaults/main.yml

  #vars:
  #  #enable_roles: true
  #  enable_roles: false

  #roles:
  #  - { role: chusiang.switch-apt-mirror, when: enable_roles == true }
  #  - { role: chusiang.vim-and-vi-mode,   when: enable_roles == true }

  tasks:
    # Main
    - name: setup gitbook
      include: tasks/main.yml

    # Check version.
    - name: check version
      command: node -v
      register: node_version
      changed_when: false

    - name: check npm version
      command: npm -v
      register: npm_version
      changed_when: false

    - name: check gitbook version
      command: gitbook -V
      register: gitbook_version
      changed_when: false

    # Print version.
    - name: print node version
      debug:
        msg: "node version: {{ node_version.stdout }}"

    - name: print npm version
      debug:
        msg: "npm version: {{ npm_version.stdout }}"

    - name: print gitbook version
      debug:
        msg: "gitbook version: {{ gitbook_version.stdout }}"

# vim: ft=yaml.ansible :
