---

# GitBook
##########

- name: install necessary package for gitbook with npm
  become: true
  npm:
    name: '{{ item }}'
    global: yes
    unsafe_perm: yes
  with_items: '{{ gitbook_npm_packages }}'

- name: fetch the specific gitbook version
  command: 'gitbook fetch {{ gitbook_specific_version }}'
  register: install_gitbook_specific_version
  changed_when: '"has been installed" in install_gitbook_specific_version'
  when: gitbook_switch_specific_version

- name: install some gitbook plugins
  command: 'gitbook install {{ gitbook_plugins }}'
  register: install_gitbook_plugins
  changed_when: '"nothing to install!" not in install_gitbook_plugins.stdout'

# vim: ft=yaml.ansible :
