---


- name: install necessary package with apt
  include: use_apt.yml
  when: ansible_pkg_mgr == "apt"

- name: install necessary package with apk
  include: use_apk.yml
  when: ansible_pkg_mgr == "apk"

- name: install necessary package with homebrew
  include: use_brew.yml
  when: ansible_pkg_mgr == "homebrew"

- name: setup node
  include: setup_node.yml

- name: setup gitbook
  include: setup_gitbook.yml

# vim: ft=ansible :
