---

# Provision
###########

# Install necessary package.
- name: install necessary package with apt
  import_tasks: use_apt.yml
  when: ansible_pkg_mgr == 'apt'

- name: install necessary package with apk
  import_tasks: use_apk.yml
  when: ansible_pkg_mgr == 'apk'

- name: install necessary package with homebrew
  import_tasks: use_brew.yml
  when: ansible_pkg_mgr == 'homebrew'

# Application
#############

- name: setup gitbook
  import_tasks: setup_gitbook.yml

# vim: ft=ansible :
