---

# Install gitbook.
- name: install gitbook with npm
  become: true
  npm:
    name: gitbook-cli
    global: yes

- name: install necessary package of gitbook
  become: true
  raw: gitbook install

- name: install some plugins of gitbook
  become: true
  raw: 'gitbook install {{ item }}'
  with_items: '{{ gitbook_plugins }}'

# vim: ft=ansible :
