---

# Run 'apt-get update'.
- name: update apt repo cache
  become: true
  apt:
    update_cache: yes

# Install packages with 'apt-get'.
- name: install packages with apt
  become: true
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - bash-completion
    - build-essential
    - curl
    - git
    - nodejs
    - nodejs-legacy
    - npm
    - rsync
    - wget
    - xdg-utils
    - xz-utils

- name: install calibre with tarball
  become: true
  shell: sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
  ignore_errors: yes

# vim: ft=ansible :
