---

# Run 'brew update'.
- name: update homebrew repo cache
  homebrew:
    update_homebrew: yes

# Run 'brew install ...'.
- name: install necessary package with homebrew
  homebrew:
    name: '{{ gitbook_necessary_brew_packages  }}'
    state: present

# vim: ft=yaml.ansible :
