---

# Run 'apk update'.
- name: update apk repo cache
  become: true
  apk:
    update_cache: yes

# Run 'sudo apk add ...'.
- name: install necessary package with apk
  become: true
  apk:
    name: '{{ item }}'
    state: present
  with_items:
    - bash
    - build-base
    - curl
    - gcc
    - git
    - nodejs
    - nodejs-npm
    - rsync

# vim: ft=ansible :
