---

# Run 'apk update'.
- name: update apk repo cache
  become: true
  apk:
    update_cache: yes

# Run 'sudo apk add ...'.
- name: install necessary package with apk
  become: true
  apk:
    name: '{{ gitbook_necessary_apk_packages }}'
    state: present

# vim: ft=yaml.ansible :
