---

# Run 'apk update'.
- name: update apt repo cache
  become: true
  apk:
    update_cache: yes

# Install packages with 'apk'.
- name: install packages with apk
  become: true
  apk:
    name: '{{ item }}'
    state: present
  with_items:
    - bash
    - build-base
    - curl
    - gcc
    - git
    - nodejs
    - nodejs-npm
    - rsync

# vim: ft=ansible :
